#!/usr/bin/env python3
import sys
import os
import csv
import argparse
import subprocess
import time

# Resolve paths relative to this script
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
CONSTANTS_FILE = os.path.join(PROJECT_ROOT, "src/main/java/frc/robot/AutoAimConstants.java")
DATA_FILE = os.path.join(SCRIPT_DIR, "autoaim_data.csv")

def clear_screen():
    os.system('cls' if os.name == 'nt' else 'clear')

def load_data():
    data = []
    if os.path.exists(DATA_FILE):
        try:
            with open(DATA_FILE, "r") as f:
                reader = csv.DictReader(f)
                for row in reader:
                    data.append({
                        "distance": float(row["distance"]),
                        "angle": float(row["angle"]),
                        "speed": float(row["speed"])
                    })
        except Exception as e:
            print(f"Error loading data: {e}")
    # Sort data by distance for cleaner interpolation and display
    return sorted(data, key=lambda x: x["distance"])

def save_data(distance, angle, speed):
    data = load_data()
    # Check for existing distance to update instead of duplicate
    updated = False
    for point in data:
        if abs(point["distance"] - distance) < 0.01:
            point["angle"] = angle
            point["speed"] = speed
            updated = True
            break
    
    if not updated:
        data.append({"distance": distance, "angle": angle, "speed": speed})
    
    data = sorted(data, key=lambda x: x["distance"])
    
    try:
        with open(DATA_FILE, "w", newline='') as f:
            writer = csv.DictWriter(f, fieldnames=["distance", "angle", "speed"])
            writer.writeheader()
            writer.writerows(data)
        print(f"\n[SUCCESS] {'Updated' if updated else 'Added'} point: Dist={distance}, Angle={angle}, Speed={speed}")
    except Exception as e:
        print(f"\n[ERROR] Could not save data: {e}")

def delete_point(index):
    data = load_data()
    if 0 <= index < len(data):
        removed = data.pop(index)
        with open(DATA_FILE, "w", newline='') as f:
            writer = csv.DictWriter(f, fieldnames=["distance", "angle", "speed"])
            writer.writeheader()
            writer.writerows(data)
        print(f"\n[SUCCESS] Removed point at distance {removed['distance']}")
    else:
        print("\n[ERROR] Invalid index")

def update_java_constants():
    if not os.path.exists(os.path.dirname(CONSTANTS_FILE)):
        os.makedirs(os.path.dirname(CONSTANTS_FILE), exist_ok=True)

    data = load_data()
    if not data:
        print("\n[ERROR] No data to sync to Java!")
        return

    # Format data into a Java double array
    data_lines = []
    for p in data:
        data_lines.append(f"        {{{p['distance']}, {p['angle']}, {p['speed']}}}")
    
    data_str = ",\n".join(data_lines)
    
    content = f"""package frc.robot;

/**
 * Constants for the Auto-Aim Interpolation Map.
 * THIS FILE IS AUTOMATICALLY GENERATED BY THE REGRESSION TOOL.
 * 
 * Data format: {{distance, angle, speed}}
 */
public final class AutoAimConstants {{
    public static final double[][] RAW_DATA = {{
{data_str}
    }};

    private AutoAimConstants() {{
        // Utility class
    }}
}}
"""
    try:
        with open(CONSTANTS_FILE, "w") as f:
            f.write(content)
        print(f"\n[SUCCESS] Synchronized {len(data)} points to {os.path.basename(CONSTANTS_FILE)}")
        
        print("Running Spotless formatter...")
        subprocess.run(["./gradlew", "spotlessApply"], cwd=PROJECT_ROOT, check=True, 
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        print("[SUCCESS] Code formatted.")
    except Exception as e:
        print(f"\n[ERROR] Failed to update Java file: {e}")

def print_table():
    data = load_data()
    if not data:
        print("\nDataset is currently empty.")
        return
    
    print("\n" + "="*45)
    print(f"{'Index':<6} | {'Distance':<10} | {'Angle':<10} | {'Speed (RPM)':<10}")
    print("-" * 45)
    for i, p in enumerate(data):
        print(f"{i:<6} | {p['distance']:<10.2f} | {p['angle']:<10.2f} | {p['speed']:<10.2f}")
    print("="*45)

def interactive_mode():
    while True:
        clear_screen()
        print("=== 2026-Bot Auto-Aim Regression Tool ===")
        print("Manage empirical data points for target interpolation.")
        print_table()
        print("\n[A] Add/Update Point  [D] Delete Point  [S] Sync to Robot Code  [Q] Quit")
        
        choice = input("\nSelection: ").strip().upper()
        
        if choice == 'Q':
            break
        elif choice == 'A':
            try:
                d = float(input("Enter Distance: "))
                a = float(input("Enter Angle: "))
                s = float(input("Enter Speed (RPM): "))
                save_data(d, a, s)
                time.sleep(1)
            except ValueError:
                print("\n[ERROR] Invalid numeric input.")
                time.sleep(1)
        elif choice == 'D':
            try:
                idx = int(input("Enter Index to delete: "))
                delete_point(idx)
                time.sleep(1)
            except ValueError:
                print("\n[ERROR] Invalid index.")
                time.sleep(1)
        elif choice == 'S':
            update_java_constants()
            input("\nPress Enter to continue...")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Auto Aim Regression Model CLI Tool")
    parser.add_argument("--sync", action="store_true", help="Sync existing CSV data to Java constants and exit")
    args = parser.parse_args()

    if args.sync:
        update_java_constants()
    else:
        try:
            interactive_mode()
        except KeyboardInterrupt:
            print("\nExiting...")
