#!/usr/bin/env python3
import sys
import os
import csv
import argparse
import subprocess
import tkinter as tk
from tkinter import ttk, messagebox

# Resolve paths relative to this script
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
CONSTANTS_FILE = os.path.join(PROJECT_ROOT, "src/main/java/frc/robot/AutoAimConstants.java")
DATA_FILE = os.path.join(SCRIPT_DIR, "autoaim_data.csv")

def load_data():
    data = []
    if os.path.exists(DATA_FILE):
        try:
            with open(DATA_FILE, "r") as f:
                reader = csv.DictReader(f)
                for row in reader:
                    data.append({
                        "distance": float(row["distance"]),
                        "angle": float(row["angle"]),
                        "speed": float(row["speed"])
                    })
        except Exception as e:
            print(f"Error loading data: {e}")
    # Sort data by distance for cleaner interpolation and display
    return sorted(data, key=lambda x: x["distance"])

def save_data(distance, angle, speed):
    data = load_data()
    # Check for existing distance to update instead of duplicate
    updated = False
    for point in data:
        if abs(point["distance"] - distance) < 0.01:
            point["angle"] = angle
            point["speed"] = speed
            updated = True
            break
    
    if not updated:
        data.append({"distance": distance, "angle": angle, "speed": speed})
    
    data = sorted(data, key=lambda x: x["distance"])
    
    try:
        with open(DATA_FILE, "w", newline='') as f:
            writer = csv.DictWriter(f, fieldnames=["distance", "angle", "speed"])
            writer.writeheader()
            writer.writerows(data)
        return True, "Success"
    except Exception as e:
        return False, str(e)

def delete_point_data(distance):
    data = load_data()
    data = [p for p in data if abs(p["distance"] - distance) >= 0.01]
    
    try:
        with open(DATA_FILE, "w", newline='') as f:
            writer = csv.DictWriter(f, fieldnames=["distance", "angle", "speed"])
            writer.writeheader()
            writer.writerows(data)
        return True
    except Exception as e:
        return False

def update_java_constants():
    if not os.path.exists(os.path.dirname(CONSTANTS_FILE)):
        os.makedirs(os.path.dirname(CONSTANTS_FILE), exist_ok=True)

    data = load_data()
    if not data:
        return False, "No data to sync to Java!"

    # Format data into a Java double array
    data_lines = []
    for p in data:
        data_lines.append(f"        {{{p['distance']}, {p['angle']}, {p['speed']}}}")
    
    data_str = ",\n".join(data_lines)
    
    content = f"""package frc.robot;

/**
 * Constants for the Auto-Aim Interpolation Map.
 * THIS FILE IS AUTOMATICALLY GENERATED BY THE REGRESSION TOOL.
 * 
 * Data format: {{distance, angle, speed}}
 */
public final class AutoAimConstants {{
    public static final double[][] RAW_DATA = {{
{data_str}
    }};

    private AutoAimConstants() {{
        // Utility class
    }}
}}
"""
    try:
        with open(CONSTANTS_FILE, "w") as f:
            f.write(content)
        
        # Run spotless formatter
        subprocess.run(["./gradlew", "spotlessApply"], cwd=PROJECT_ROOT, check=True, 
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        return True, f"Synchronized {len(data)} points to Java and formatted code."
    except Exception as e:
        return False, f"Failed to update Java file: {e}"


class AutoAimGUI(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("2026-Bot Auto-Aim Interpolation Manager")
        self.geometry("650x450")
        
        # Style
        style = ttk.Style(self)
        if "clam" in style.theme_names():
            style.theme_use("clam")

        # Main Container
        main_frame = ttk.Frame(self, padding="10")
        main_frame.pack(fill=tk.BOTH, expand=True)

        # Table Frame
        table_frame = ttk.LabelFrame(main_frame, text=" Empirical Data Points ", padding="5")
        table_frame.pack(fill=tk.BOTH, expand=True, pady=(0, 10))

        columns = ("Distance", "Angle", "Speed")
        self.tree = ttk.Treeview(table_frame, columns=columns, show="headings", selectmode="browse")
        
        for col in columns:
            self.tree.heading(col, text=col)
            self.tree.column(col, width=180, anchor=tk.CENTER)
            
        scrollbar = ttk.Scrollbar(table_frame, orient=tk.VERTICAL, command=self.tree.yview)
        self.tree.configure(yscroll=scrollbar.set)
        
        self.tree.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
        
        self.tree.bind('<<TreeviewSelect>>', self.on_select)

        # Input Frame
        input_frame = ttk.Frame(main_frame)
        input_frame.pack(fill=tk.X, pady=(0, 10))

        ttk.Label(input_frame, text="Distance:").grid(row=0, column=0, padx=(0,5), pady=5, sticky=tk.W)
        self.dist_var = tk.StringVar()
        ttk.Entry(input_frame, textvariable=self.dist_var, width=12).grid(row=0, column=1, padx=(0,15), pady=5)

        ttk.Label(input_frame, text="Angle:").grid(row=0, column=2, padx=(0,5), pady=5, sticky=tk.W)
        self.angle_var = tk.StringVar()
        ttk.Entry(input_frame, textvariable=self.angle_var, width=12).grid(row=0, column=3, padx=(0,15), pady=5)

        ttk.Label(input_frame, text="Speed (RPM):").grid(row=0, column=4, padx=(0,5), pady=5, sticky=tk.W)
        self.speed_var = tk.StringVar()
        ttk.Entry(input_frame, textvariable=self.speed_var, width=12).grid(row=0, column=5, padx=(0,0), pady=5)

        # Button Frame
        btn_frame = ttk.Frame(main_frame)
        btn_frame.pack(fill=tk.X)

        ttk.Button(btn_frame, text="Add / Update", command=self.add_point).pack(side=tk.LEFT, padx=(0, 5))
        ttk.Button(btn_frame, text="Delete Selected", command=self.delete_point).pack(side=tk.LEFT, padx=5)
        
        sync_btn = ttk.Button(btn_frame, text="Sync to Robot Code", command=self.sync_code)
        sync_btn.pack(side=tk.RIGHT)

        self.refresh_table()

    def refresh_table(self):
        for item in self.tree.get_children():
            self.tree.delete(item)
        data = load_data()
        for p in data:
            self.tree.insert("", tk.END, values=(f"{p['distance']:.2f}", f"{p['angle']:.2f}", f"{p['speed']:.2f}"))

    def on_select(self, event):
        selected = self.tree.selection()
        if selected:
            values = self.tree.item(selected[0], "values")
            self.dist_var.set(values[0])
            self.angle_var.set(values[1])
            self.speed_var.set(values[2])

    def add_point(self):
        try:
            d = float(self.dist_var.get())
            a = float(self.angle_var.get())
            s = float(self.speed_var.get())
            success, msg = save_data(d, a, s)
            if success:
                self.refresh_table()
                self.dist_var.set("")
                self.angle_var.set("")
                self.speed_var.set("")
            else:
                messagebox.showerror("Error", f"Failed to save data: {msg}")
        except ValueError:
            messagebox.showwarning("Input Error", "Please enter valid numeric values for all fields.")

    def delete_point(self):
        selected = self.tree.selection()
        if not selected:
            messagebox.showinfo("Selection", "Please select a data point from the table to delete.")
            return
        
        values = self.tree.item(selected[0], "values")
        distance = float(values[0])
        
        if messagebox.askyesno("Confirm Delete", f"Delete the data point at Distance {distance}?"):
            if delete_point_data(distance):
                self.refresh_table()
                self.dist_var.set("")
                self.angle_var.set("")
                self.speed_var.set("")
            else:
                messagebox.showerror("Error", "Failed to delete the data point.")

    def sync_code(self):
        success, msg = update_java_constants()
        if success:
            messagebox.showinfo("Sync Successful", msg)
        else:
            messagebox.showerror("Sync Failed", msg)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Auto Aim Regression GUI Tool")
    parser.add_argument("--sync", action="store_true", help="Sync existing CSV data to Java constants without opening GUI")
    args = parser.parse_args()

    if args.sync:
        success, msg = update_java_constants()
        print(msg)
        sys.exit(0 if success else 1)
    else:
        try:
            app = AutoAimGUI()
            app.mainloop()
        except KeyboardInterrupt:
            print("\nExiting GUI...")
