name: Bug Report
description: Report a bug or unexpected behavior in the robot code
title: "[Bug] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us diagnose and fix the issue.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (Robot won't run / Safety issue)
        - High (Major functionality broken)
        - Medium (Feature partially broken)
        - Low (Minor issue / Cosmetic)
    validations:
      required: true

  - type: dropdown
    id: location
    attributes:
      label: Where does this occur?
      description: Select all that apply
      multiple: true
      options:
        - Competition Robot
        - Practice Robot
        - Simulation
        - Build System
        - Unknown
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what's broken and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Enable teleop mode
        2. Move joystick forward
        3. Observe behavior
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: Describe what actually happens
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Include any relevant console output, error messages, or stack traces
      placeholder: Paste logs here
      render: shell

  - type: input
    id: commit
    attributes:
      label: Git Commit / Branch
      description: What commit or branch exhibits this bug?
      placeholder: "main / a1b2c3d"

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or videos about the problem
      placeholder: Any additional information that might help

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have tested this on the latest code
          required: false
        - label: I have included all relevant information above
          required: true
