name: Feature Request
description: Suggest a new feature or enhancement for the robot
title: "[Feature] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area does this feature relate to?
      options:
        - Autonomous
        - Drivetrain / Swerve
        - Vision / Sensors
        - Game Mechanism (Intake, Shooter, etc.)
        - Driver Interface / Controls
        - Telemetry / Logging
        - Simulation
        - Build System / CI
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical (Needed for competition)
        - High (Significant improvement)
        - Medium (Nice to have)
        - Low (Future consideration)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What is the current limitation?
      placeholder: Describe the problem or limitation this addresses
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or implementation
      placeholder: How should this feature work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or features have you considered?
      placeholder: Describe any alternative approaches

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Details
      description: Technical details, dependencies, or implementation notes
      placeholder: |
        - Required libraries/dependencies
        - Code changes needed
        - Configuration changes
        - Testing requirements

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, diagrams, or links
      placeholder: Any additional information

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following
      options:
        - label: I have searched existing issues and PRs to avoid duplicates
          required: true
        - label: This feature aligns with the team's goals and competition strategy
          required: false
        - label: I have considered the time/effort required for implementation
          required: false
